name: life_rpg
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^9.1.0
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.5.1
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.9.0
  path_provider: ^2.1.4
  riverpod_annotation: ^2.3.5


dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
